In [147]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
import markovchain

In [148]:
mc_example = {'NYC': [.25,0,.75,1],
              'Paris': [.25,.25,0,0],
              'Cairo': [.25,.25,.25,0],
              'Seoul': [.25,.5,0,0]}

mc = pd.DataFrame(data = mc_example, index = ['NYC', 'Paris', 'Cairo', 'Seoul'])

In [149]:
mc

NYC  Paris  Cairo  Seoul
NYC    0.25   0.25   0.25   0.25
Paris  0.00   0.25   0.25   0.50
Cairo  0.75   0.00   0.25   0.00
Seoul  1.00   0.00   0.00   0.00

In [150]:
travel_sim = []
travel_sim.append(mc.iloc[0].index[0])

In [151]:
travel_sim

['NYC']

In [152]:
print(mc.iloc[0].index)

Index(['NYC', 'Paris', 'Cairo', 'Seoul'], dtype='object')


In [153]:
print(mc.iloc[0])

NYC      0.25
Paris    0.25
Cairo    0.25
Seoul    0.25
Name: NYC, dtype: float64


In [154]:
next_city = np.random.choice(mc.iloc[0].index ,p=mc.iloc[0])
travel_sim.append(next_city)
travel_sim

['NYC', 'Paris']

In [166]:
testcity = 'Seoul'
mc.iloc[mc.index.get_loc(testcity)]
#mc.index.get_loc(testcity)
next_city = ('Cairo')

In [179]:
travel_sim = []
while len(travel_sim) < 25:
    next_city = np.random.choice(mc.iloc[mc.index.get_loc(next_city)].index, p=mc.iloc[mc.index.get_loc(next_city)])
    travel_sim.append(next_city)
print(travel_sim)

['NYC', 'Seoul', 'NYC', 'Cairo', 'Cairo', 'NYC', 'Seoul', 'NYC', 'Seoul', 'NYC', 'Seoul', 'NYC', 'Paris', 'Paris', 'Seoul', 'NYC', 'Paris', 'Seoul', 'NYC', 'Paris', 'Seoul', 'NYC', 'NYC', 'Paris', 'Seoul']


In [183]:
marcov_chain_matrix = mc.to_numpy()
marcov_chain_matrix

array([[0.25, 0.25, 0.25, 0.25],
       [0.  , 0.25, 0.25, 0.5 ],
       [0.75, 0.  , 0.25, 0.  ],
       [1.  , 0.  , 0.  , 0.  ]])

In [181]:
# the following functions multiples marcov_chain_matrix by itself 
def matrix_power(matrix, power):
  if power == 0:
    return np.identity(len(matrix))
  elif power == 1:
    return matrix
  else:
    return np.dot(matrix, matrix_power(matrix, power-1))

In [184]:
# this means if you take 0 steps you will end up where you are!!!
matrix_power(marcov_chain_matrix, 0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [188]:
# if we set power to a large enough number
matrix_power(marcov_chain_matrix, 10)

array([[0.45569897, 0.15189743, 0.20253086, 0.18987274],
       [0.45570278, 0.15189743, 0.20252991, 0.18986988],
       [0.45569229, 0.15190029, 0.20253277, 0.18987465],
       [0.45568848, 0.15190125, 0.20253372, 0.18987656]])

In [192]:
# this shows us if we start in cairo(because of initial_dist)
# and take 2 steps (because of power = 2) how much is the chance
# of ending in each city
initial_dist = np.asarray([0,0,1,0])

mc_p2 = matrix_power(marcov_chain_matrix,2)

np.dot(initial_dist,mc_p2)

array([0.375 , 0.1875, 0.25  , 0.1875])